#!/bin/sh

if [ $# -eq 0 ]; then
    echo "Usage: ./run <firmware name>"
    exit 1
fi

FIRMWARE_NAME=$1
if [ ! -d "${FIRMWARE_NAME}" ]; then
    echo "ERROR: ./${FIRMWARE_NAME} no such directory"
    exit 1
fi

VIVADO=/home/oyaji/opt/Xilinx/Vivado/2017.4/bin/

################################################################################
# Create build directory

BUILD_DIR="${FIRMWARE_NAME}/build"
rm -rf ${BUILD_DIR}
mkdir -p ${BUILD_DIR}
cd ${BUILD_DIR}

figlet -f slant "${FIRMWARE_NAME}"
${VIVADO}/vivado -mode batch -source ../script.tcl
