#!/bin/sh

if [ $# -eq 0 ]; then
    echo "Usage: ./$(basename "$0") <firmware name>"
    exit 1
fi

FIRMWARE_NAME=$1
if [ ! -d "${FIRMWARE_NAME}" ]; then
    echo "ERROR: ./${FIRMWARE_NAME} no such directory"
    exit 1
fi

################################################################################
# Create build directory

BUILD_DIR="${FIRMWARE_NAME}/build"
rm -rf ${BUILD_DIR}
mkdir -p ${BUILD_DIR}
cd ${BUILD_DIR}

figlet -w 200 -f slant "${FIRMWARE_NAME}"
vivado -mode batch -source ../script.tcl
